// flow-typed signature: 710006b2fbcf5fb3026f0415b9350620
// flow-typed version: <<STUB>>/react-mobx_v^0.0.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mobx/build/webpack.base' {
  declare module.exports: any;
}

declare module 'react-mobx/build/webpack.build' {
  declare module.exports: any;
}

declare module 'react-mobx/build/webpack.dev' {
  declare module.exports: any;
}

declare module 'react-mobx/config/dev-client' {
  declare module.exports: any;
}

declare module 'react-mobx/config/dev' {
  declare module.exports: any;
}

declare module 'react-mobx/config/index' {
  declare module.exports: any;
}

declare module 'react-mobx/config/prod' {
  declare module.exports: any;
}

declare module 'react-mobx/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mobx/build/webpack.base.js' {
  declare module.exports: $Exports<'react-mobx/build/webpack.base'>;
}
declare module 'react-mobx/build/webpack.build.js' {
  declare module.exports: $Exports<'react-mobx/build/webpack.build'>;
}
declare module 'react-mobx/build/webpack.dev.js' {
  declare module.exports: $Exports<'react-mobx/build/webpack.dev'>;
}
declare module 'react-mobx/config/dev-client.js' {
  declare module.exports: $Exports<'react-mobx/config/dev-client'>;
}
declare module 'react-mobx/config/dev.js' {
  declare module.exports: $Exports<'react-mobx/config/dev'>;
}
declare module 'react-mobx/config/index.js' {
  declare module.exports: $Exports<'react-mobx/config/index'>;
}
declare module 'react-mobx/config/prod.js' {
  declare module.exports: $Exports<'react-mobx/config/prod'>;
}
declare module 'react-mobx/src/index.js' {
  declare module.exports: $Exports<'react-mobx/src/index'>;
}
