// flow-typed signature: 6192152abda6dd3ad5beb8b2720317f0
// flow-typed version: <<STUB>>/react-timezone_v^2.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-timezone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-timezone/build/react-timezone.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-timezone/build/react-timezone.min.js' {
  declare module.exports: $Exports<'react-timezone/build/react-timezone.min'>;
}
